# Generated by Django 5.1.4 on 2025-01-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='url',
            field=models.CharField(default='/', max_length=255),
        ),
    ]
