# Generated by Django 5.1.4 on 2025-01-30 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_notifications', '0005_remove_usernotification_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='sender',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('bid', 'New Bid'), ('hire', 'Hired for Project'), ('message', 'New Message'), ('file', 'File Activity'), ('project', 'Project Update')], default='/', max_length=20),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
