# Generated by Django 5.1.4 on 2025-01-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_notifications', '0007_remove_usernotification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(default='/', max_length=50),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
