# Generated by Django 5.1.4 on 2025-01-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('hired', 'Hired'), ('just_started', 'Just Started'), ('intermediate', 'Intermediate'), ('completed', 'Completed'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete')], default='open', max_length=20),
        ),
    ]
